#!/bin/bash

# rename mesh to all uppercase if it's not
if [ -d "/var2/mars/MeSH" ]; then
  mv /var2/mars/MeSH /var2/mars/MESH
  echo "renaming MeSH to MESH"
fi

FOLDERS=( "Genre" "LCSH" "MESH" "MISC" "MST" "MU" "MU_HSL" "MU_LAW" "NTAR" "UMKC" "UMKC_LAW" "UMSL" "XLS" "Manual" "xls")

DATE=`date +%Y%m%d`
echo "$DATE"

#archive all the stuff
sudo tar -czf /home/mcohelp/mars/archive/$DATE.tar.gz /var2/mars
sudo chown -R mcohelp:mco "/home/mcohelp/mars/archive/$DATE.tar.gz"

for i in "${FOLDERS[@]}"
do 
  if [ -d "/home/mcohelp/mars/$i" ]; then
    sudo rm -R "/home/mcohelp/mars/$i"
  fi
done

for i in "${FOLDERS[@]}"
do 
  if [ -d "/var2/mars/$i" ]; then
    cp "/var2/mars/$i" "/home/mcohelp/mars/$i" -R
    sudo chown -R mcohelp:mco "/home/mcohelp/mars/$i"
  fi
done
